# Generated by Django 5.2.1 on 2025-06-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(db_column='categoria_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(db_column='producto_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('descripción', models.TextField(db_column='descripción')),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('cantidad_en_stock', models.IntegerField(db_column='cantidad_en_stock')),
                ('imagen', models.CharField(blank=True, db_column='imagen', max_length=255, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
